### ISSUE TITLE
Recorded sessions access right issue

### ISSUE THREAD

**Issue by wirepatch** [Minervis-GmbH/BigBlueButton-Ilias-Plugin#1]
Recording a BigBlueButton session starting from ILIAS results in a link being added subsequently e.g.:
```
date 
31.03.2020 13:33 | link | delete recording
31.03.2020 13:31 | link | delete recording
```
The faksimile above shows a course administrator's view. A course member however will not see any of these links unless being granted the »edit session« privilege.

On the other hand granting »edit session« allows for editing title, description, welcome text and even set the BigBlueButton classrom in question to »offline«.

I wonder why Ilias's usual »Visible« and »Read« permissions are insufficient for accessing links to recorded videos as well.

**Comment by rfcmaXi** [comment]
The delivery of videos to normal course members was simply not implemented in the template (tpl.BigBlueButtonClient.html), instead it was only implemented for course administrators (tpl.BigBlueButtonModeratorClient.html). 

I didn't find this very useful either, so I implemented it locally (without the delete command, of course). Whether this makes sense in all scenarios, I can't decide.
