### ISSUE TITLE
Compatibility to BBB 2.3

### ISSUE THREAD

**Issue by thwien** [Minervis-GmbH/BigBlueButton-Ilias-Plugin#18]
Does the Ilias plugin been tested against BBB 2.3 already?

We are planning to upgrade from BBB 2.2 to 2.3 behind a Scalelite load balancer version 1.1.

**Comment by jeph864** [comment]
Dear @thwien,
We have tested the plugin against 2.3! and there were no  issues found!

**Comment by thwien** [comment]
Thanks a lot for your reply.
