### ISSUE TITLE
May Legth of Security Salt

### ISSUE THREAD

**Issue by wolfganghuebsch** [Minervis-GmbH/BigBlueButton-Ilias-Plugin#20]
Hi,

I have Version 1.0.15 here, and when I try to upadte the salt, this happens:

Security Salt *
Das Passwort darf höchstens 20 Zeichen lang sein.

The salt length is 35

Cheers,
Wolfgang

**Comment by jeph864** [comment]
Hi @wolfganghuebsch ,
It came to our attention that the the Server-salt field in the configuration form follows that ILIAS password guidelines! In our next release this issue will be solved. However if you cant wait for the next release you can edit the following piece of code from classes/class.ilBigBlueButtonConfigGUI.php on line 94:
`		// salt (text)
		$pi = new ilPasswordInputGUI($pl->txt("salt"), "frmsalt");
		$pi->setRequired(true);
		$pi->setMaxLength(256);`
to
 `// salt (text)
		$pi = new ilPasswordInputGUI($pl->txt("salt"), "frmsalt");
		$pi->setSkipSyntaxCheck(true);
		$pi->setRequired(true);
		$pi->setMaxLength(256);`
