### ISSUE TITLE
Ilias 7.6 working as well

### ISSUE THREAD

**Issue by wirepatch** [Minervis-GmbH/BigBlueButton-Ilias-Plugin#23]
You may want to update your main  `Readme.md` file adding Ilias 7.6 support. I've just finished some preliminary tests. So far no errors encountered. Keep my fingers crossed!

**Comment by xJuvi** [comment]
I've created PR #25
Thanks for testing

**Comment by jeph864** [comment]
Dear @wirepatch and @xJuvi thanks for the contribution. I have accepted the  PR #25
