### ISSUE TITLE
[BBB 2.4.5] Error: You can not join a meeting that has already been forcibly ended

### ISSUE THREAD

**Issue by D33M0N** [Minervis-GmbH/BigBlueButton-Ilias-Plugin#26]
installed fresh BBB 2.4.5 and the current master branch BigBlueButton-Ilias-Plugin (1.0.15 I assume; Ilias 5.4.23)

Now. Activated it. Configured it. And when I try to create a new BBB instance with this Ilias plugin here, I get the error:
`Error: You can not join a meeting that has already been forcibly ended`

![image](https://user-images.githubusercontent.com/15782020/162442873-208bec4d-161c-4a53-a3f0-c442e2902857.png)

**Comment by D33M0N** [comment]
Just to mention, previously had plugin version 1.0.13 working with BBB 2.2 and it works perfectly.
Installed new separate server with BBB 2.4 and the previous plugin failed to work with it with the same exact error as above.
Upgraded plugin to 1.0.15 (or whatever came with git clone like in install instruction) and still the same problem.

**Comment by jeph864** [comment]
Dear @D33M0N ,
is it possible to join bigbluebutton  rooms when you use other clients such as the default html5client, greenlight or even APIMate??

**Comment by D33M0N** [comment]
> Dear @D33M0N , is it possible to join bigbluebutton rooms when you use other clients such as the default html5client, greenlight or even APIMate??

it is totally possible to join with the BBB install inbuilt "API demos" thing (have not removed it yet, because the new server is not going live before I can solve this plugin issue). So BBB itself seems to work fine.

**Comment by jeph864** [comment]
I haven't encountered this error with 2.4 yet, So I'll need a bit  more time to reproduce this. Meanwhile there is a newer version of the plugin(see  [branch release2.0](https://github.com/Minervis-GmbH/BigBlueButton-Ilias-Plugin/tree/release2.0)), which has more advances by the way and uses an improved api client

**Comment by D33M0N** [comment]
> I haven't encountered this error with 2.4 yet, So I'll need a bit more time to reproduce this.

2.4.5 to be specific.

> Meanwhile there is a newer version of the plugin(see [branch release2.0](https://github.com/Minervis-GmbH/BigBlueButton-Ilias-Plugin/tree/release2.0)), which, by the way, has more advanced features and uses an improved API client. You can try it out and let me know.

if I go the release 2.0 *BETA* route, then is there a way to downgrade back? so far it seems I can only upgrade because it alters the database or whatever. Or how can I completely remove this plugin and start fresh? ( I assume just deleting the filed from plugins folder doesn't do the trick and I need to remove the relevant tables from database? right? but where and what and how? )

**Comment by D33M0N** [comment]
Alright. Replaced the 1.0.15 with Release 2.0, ran the update (it did say it applied updates 4,5,6,7,8). But still the result is the same. Meanwhile checked Ilias version also and updated the initial post - it's 5.4.23 not 5.3.xx.
Also the exact same error with both Firefox 98.0.2 and Brave V1.37.111 (Apr 5, 2022), based on Chromium 100.0.4896.79.

**Comment by D33M0N** [comment]
Tested this new server also with the API Mate URL provided by `bbb-conf --secret` and it also works perfectly.

**Comment by jeph864** [comment]
So, if the the peer verification is deactivated in CURL, does the issue remain ?

**Comment by D33M0N** [comment]
> So, if the the peer verification is deactivated in CURL, does the issue remain ?

Yes. Because those 2 problems are unrelated I think. Also 2 different servers with vastly different setup (internal; with self signed cert; old BBB with old Ubuntu 16.04 vs new BBB with newer Ubuntu 18.04, legit cert and everything).

**Comment by jeph864** [comment]
alright! We will investigate this further.

**Comment by D33M0N** [comment]
Are you using the newest BBB API? (inside the files I see dates (c) 2016-2018; maybe still unchanged, just wondering)
Also looking through the files in vendor/bigbluebutton/bigbluebutton-api-php/ it seems that the default value for hasBeenForciblyEnded variable is `true` for some reason.
Do you set it explicitly to false when creating a new meeting (just in case asking "stupid" questions, sorry about it)?

**Comment by D33M0N** [comment]
> alright! We will investigate this further.

any luck? :-)

**Comment by jeph864** [comment]
@D33M0N ,
the issue has been forwarded to the team! They're on it

**Comment by xJuvi** [comment]
Hi there,
i can agree with this error. Yesterday we need to update ilias to version 7.11. This requires the bbb plugin 1.1.15. Since the plugin update we had the same error. BBB shows the following in logs:

> /var/log/bigbluebutton/bbb-web.log:2022-07-12T06:43:33.497Z ERROR o.b.web.controllers.ApiController - You can not join a meeting that has already been forcibly ended
/var/log/bigbluebutton/bbb-web.log:2022-07-12T06:43:33.497Z ERROR o.b.web.controllers.ApiController - The provided password is neither a moderator or attendee password
/var/log/bigbluebutton/bbb-web.log:2022-07-12T06:43:33.497Z ERROR o.b.web.controllers.ApiController - A meeting with that ID does not exist
/var/log/bigbluebutton/bbb-web.log:2022-07-12T06:45:05.842Z ERROR o.b.web.controllers.ApiController - You can not join a meeting that has already been forcibly ended
/var/log/bigbluebutton/bbb-web.log:2022-07-12T06:45:05.842Z ERROR o.b.web.controllers.ApiController - The provided password is neither a moderator or attendee password
/var/log/bigbluebutton/bbb-web.log:2022-07-12T06:45:05.842Z ERROR o.b.web.controllers.ApiController - A meeting with that ID does not exist

Now we downgrade the plugin to v1.1.2 and changed manually the plugin.php file to use this version with ilias 7. After changed the file we can use bbb again without error.

Kind regards

**Comment by xJuvi** [comment]
So I had updated this plugin to the version 2 branch. It's working without the error. 
No error while join the room.

**Comment by D33M0N** [comment]
> So I had updated this plugin to the version 2 branch. It's working without the error.
> No error while join the room.

But you are using way newer Ilias. (7 vs my 5th.) Also what version of BBB are you using?
Also meanwhile I see there has been some development with the plugin itself in Branch 2, but no new "release". Maybe something got fixed there with the patches?

**Comment by xJuvi** [comment]
The ilias version should not be nessesary. This plugin doesn't use much ilias classes.
I use BB version 2.4.5.

You can change the git branch to fetch the version 2.0 - there are much fixes for plugn version 1.1.x- Also the own BBB api was replaced by the official BBB api - so is should run smoother.

**Comment by D33M0N** [comment]
YEY!! upgraded the plugin from master (2.0 some iteration right now) and everything seems to work now.
