### ISSUE TITLE
Plugin 2.0 release doesn't work with Ilias 5.4.23 / BBB 2.2 (self signed cert problem)

### ISSUE THREAD

**Issue by D33M0N** [Minervis-GmbH/BigBlueButton-Ilias-Plugin#27]
after you suggested upgrading plugin to 2.0.0 here https://github.com/Minervis-GmbH/BigBlueButton-Ilias-Plugin/issues/26
and I did, (still didn't work there with BBB 2.4.5), I can't switch back now to old BBB 2.2 either, because it just fails in ilias with "server not reachable" error. API mate links work perfectly.

**Comment by jeph864** [comment]
Dear @D33M0N ,
if you get that error, it simply means that the public URL is wrong! The function which returns that message only checks the reachability of the bbb-api. Would you like to share the format of the URL you're using? Also keep in mind that the plugin beta version(1.0.19) now has a production ready version(in branch release2.0)

**Comment by D33M0N** [comment]
> if you get that error, it simply means that the public URL is wrong!

Well. it's not wrong (unless the accepted format changed?). `https://3b-test.domain.intra/bigbluebutton/` format. Used this before with 1.0.12 and it worked fine. Works also with API Mate.

**Comment by jeph864** [comment]
is it the same for plugin version 2.0?

**Comment by D33M0N** [comment]
> is the response the same also for plugin version 2.0?

the plugin IS 2.0. stuck to it. there is no way to "downgrade" it. at least I have no clue how to go back to previous. It did update the database and there is no database downgrade script, or is there?

**Comment by D33M0N** [comment]
> Also keep in mind that the plugin beta version(1.0.19) now has a production ready version(in branch release2.0)

you lost me here. I only see master (no idea what version) and "release1_0_15" (which I tried previously with BBB 2.4.5 and didn't work) and "release2.0" to which I upgraded and it still didn't work... and also fails to connect back to previous BBB 2.2 instance.
![image](https://user-images.githubusercontent.com/15782020/163155032-97fedffa-cea7-489d-af82-ccbd3222aeb7.png)

**Comment by jeph864** [comment]
here is the piece of code which is responsible for the reachability check:
![Screenshot from 2022-04-13 12-05-13](https://user-images.githubusercontent.com/57417057/163155084-2f61fc27-c695-4fe9-a0a9-d5f372f6162f.png)

This is sends a GET request to {YOUR_URL}/bigbluebutton/api. You can check what's the exception message is and let me know(it's line 189 in file https://github.com/Minervis-GmbH/BigBlueButton-Ilias-Plugin/blob/release2.0/classes/class.ilBigBlueButtonConfigGUI.php)

**Comment by jeph864** [comment]
> And they all are months old. Did you forget to upload your changes to github

Hahhh kind of but not entirely, the  release2.0 is the latest. We wanted to make this  the default  branch after getting enough feedback from the community.

**Comment by D33M0N** [comment]
how can I check which version of the plugin I actually really have installed? this git here is a bit confusing?
if I remember correctly, I did download it from:
https://github.com/Minervis-GmbH/BigBlueButton-Ilias-Plugin/tree/release2.0
Code > Download ZIP (because the links in all the branches/releases seemed identical... so couldn't use git pull)

> You can check what's the exception message is

how exactly I do that?

**Comment by D33M0N** [comment]
FOUND ERROR!! it does not like locally signed certificate and fails thus. It should use curl flag to bypass this check!

**Comment by jeph864** [comment]
> how can I check which version of the plugin I actually really have installed? this git here is a bit confusing?

You can check in the plugin administration(Bigbluebutton>Action>information)

**Comment by jeph864** [comment]
> FOUND ERROR!! it does not like locally signed certificate and fails thus. It should use curl flag to bypass this check!

Hooray! issue resolved. since that's a personal security issue, we can't implement that in the official version. But you can set the flag locally in your plugin

**Comment by D33M0N** [comment]
> You can check in the plugin administration(Bigbluebutton>Action>information)

have the fields translated, so no idea about the original english field names, but goes something like this:

version 2.0
min ilias version 4.0.0
max ilias version 7.99
db
file dbupdate.php
current version 8
update file version 8

**Comment by jeph864** [comment]
> version 2.0

that's the installed version

**Comment by D33M0N** [comment]
> since that's a personal security issue, we can't implement that in the official version. But you can set the flag locally in your plugin.

still unelegant solution. certificate authenticity should not be concern to this plugin. and/or if you want, you could just inform the user about the problem with cert, not just say it's unreachable. frankly not even any browser complains. not quite sure why curl does.

**Comment by jeph864** [comment]
What we can do in the plugin is improve  the message to indicate that there is a certs issue. 
Regarding whether the certificate authenticity should be a concern or not, you can suggest a feature in the official php bigbluebutton-api (https://github.com/bigbluebutton/bigbluebutton-api-php.git). this plugin is based on that  official php api  client

**Comment by D33M0N** [comment]
well the relevant change in the 2.0 release is:
https://github.com/Minervis-GmbH/BigBlueButton-Ilias-Plugin/blob/release2.0/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php
line 461 and CURLOPT_SSL_VERIFYPEER value should be set to 0 (currently 1).

**Comment by D33M0N** [comment]
> this is the installed version

so, is there any "newer" version than this 2.0 or this should be like the "last"? :-)
Priority is to get the BBB 2.4.5 to work now. Which is in another [issue](https://github.com/Minervis-GmbH/BigBlueButton-Ilias-Plugin/issues/26).

**Comment by jeph864** [comment]
> line 461 and CURLOPT_SSL_VERIFYPEER value should be set to 0 (currently 1).

As mentioned, the implementation of this is on the side of the official bbb api client(linked in my earlier comments). you can make a feature suggestion there and once it's implemented there, we can accept it here in the plugin. though I doubt that the suggestion will be accepted.
I'm closing the issue.
