### ISSUE TITLE
Can not create room

### ISSUE THREAD

**Issue by wolfganghuebsch** [Minervis-GmbH/BigBlueButton-Ilias-Plugin#37]
Hi,

with the newest Plugin version, I get this error:

BigBlueButton\Exceptions\BadResponseException thrown with message "Bad response, HTTP code: 501"

Stacktrace:
#10 BigBlueButton\Exceptions\BadResponseException in /var/www/html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/BigBlueButton/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:488
#9 BigBlueButton\BigBlueButton:processXmlResponse in /var/www/html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/BigBlueButton/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:264
#8 BigBlueButton\BigBlueButton:getMeetingInfo in /var/www/html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/BigBlueButton/classes/class.ilBigBlueButtonProtocol.php:147
#7 ilBigBlueButtonProtocol:isMeetingRecorded in /var/www/html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/BigBlueButton/classes/class.ilObjBigBlueButtonGUI.php:373
#6 ilObjBigBlueButtonGUI:showContent in /var/www/html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/BigBlueButton/classes/class.ilObjBigBlueButtonGUI.php:98
#5 ilObjBigBlueButtonGUI:performCommand in /var/www/html/ilias/Services/Repository/classes/class.ilObjectPluginGUI.php:165
#4 ilObjectPluginGUI:executeCommand in /var/www/html/ilias/Services/UICore/classes/class.ilCtrl.php:217
#3 ilCtrl:forwardCommand in /var/www/html/ilias/Services/Repository/classes/class.ilObjPluginDispatchGUI.php:45
#2 ilObjPluginDispatchGUI:executeCommand in /var/www/html/ilias/Services/UICore/classes/class.ilCtrl.php:217
#1 ilCtrl:forwardCommand in /var/www/html/ilias/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /var/www/html/ilias/ilias.php:23

-- GET Data --

ref_id                   : 350604
cmd                      : showContent
cmdClass                 : ilobjbigbluebuttongui
cmdNode                  : r6:me
baseClass                : ilobjplugindispatchgui
lang                     : de
limit                    : 9999

-- POST Data --

empty

-- Files --

empty

-- Cookies --

ilClientId               : iliasschoolmaster
PHPSESSID                : pl9e2oa7gluokgthrnu0bujsud
il_mb_slates             : {"engaged":true}
1044257661               : {"any_entry_engaged":true,"tools_engaged":false,"more_available":true,"entries":{"0:0":[0,0,0],"0:1":[0,1,0],"0:1:0":[0,1,0],"0:1:8":[0,0,0],"0:2":[0,0,0],"0:3":[0,0,0],"0:4":[0,0,0],"0:5":[0,0,0],"0:6":[0,0,0],"0:7":[0,0,0],"0:7:0":[0,0,0],"0:7:1":[0,1,0],"0:7:3":[0,1,0],"0:7:4":[0,0,0],"0:7:5":[0,0,0],"0:7:6":[0,0,0],"0:7:8":[0,0,0],"0:7:9":[0,1,0],"0:7:10":[0,0,0],"0:8":[0,0,0],"0:9":[0,0,0]},"tools":{},"known_tools":[],"last_active_top":"0:1"}

-- Session --

tbl_limit                : 9999
referer_ref_id           : 350604
_authsession_expired     : 0
SessionType              : 2
_authsession_authenticated: 1
_authsession_user_id     : 431
orig_request_target      : 
has_to_accept_agr_in_session: 1
lang                     : de
ILIAS\Init\StartupSequence\StartUpSequenceDispatcher_passed: 1
il_pd_history            : 
pditems_0_blnav          : ::0
pdmem_0_blnav            : ::0
pdtasks_0_blnav          : ::0
pdnews_0_blnav           : ::0
pdmail_0_blnav           : ::0
awrn_last_update         : 1669647158
awrn_nr_users            : 119
awrn_nr_husers           : 0
il_rep_mode              : flat
il_rep_ref_id            : 79685
il_nav_history           : a:4:{s:7:"350604:";a:7:{s:2:"id";s:7:"350604:";s:6:"ref_id";s:6:"350604";s:4:"link";s:80:"https://kivinet.de/ilias/goto.php?target=xbbb_350604&client_id=iliasschoolmaster";s:5:"title";s:1:"3";s:4:"type";s:4:"xbbb";s:10:"sub_obj_id";s:0:"";s:9:"goto_link";s:0:"";}s:6:"79685:";a:7:{s:2:"id";s:6:"79685:";s:6:"ref_id";s:5:"79685";s:4:"link";s:78:"https://kivinet.de/ilias/goto.php?target=grp_79685&client_id=iliasschoolmaster";s:5:"title";s:14:"Muster - Kopie";s:4:"type";s:3:"grp";s:10:"sub_obj_id";s:0:"";s:9:"goto_link";s:0:"";}s:7:"348541:";a:7:{s:2:"id";s:7:"348541:";s:6:"ref_id";s:6:"348541";s:4:"link";s:80:"https://kivinet.de/ilias/goto.php?target=xbbb_348541&client_id=iliasschoolmaster";s:5:"title";s:1:"6";s:4:"type";s:4:"xbbb";s:10:"sub_obj_id";s:0:"";s:9:"goto_link";s:0:"";}s:7:"350600:";a:7:{s:2:"id";s:7:"350600:";s:6:"ref_id";s:6:"350600";s:4:"link";s:80:"https://kivinet.de/ilias/goto.php?target=xbbb_350600&client_id=iliasschoolmaster";s:5:"title";s:1:"2";s:4:"type";s:4:"xbbb";s:10:"sub_obj_id";s:0:"";s:9:"goto_link";s:0:"";}}
news_99891_blnav         : ::0
table                    : Array
                         (
                             [cmpspl] => Array
                                 (
                                     [431] => Array
                                         (
                                             [offset] => 0
                                         )
                         
                                 )
                         
                         )
                         
referer                  : /ilias/ilias.php?ref_id=350604&cmd=editProperties&cmdClass=ilobjbigbluebuttongui&cmdNode=r6:me&baseClass=ilobjplugindispatchgui

-- Server/Request Data --

SCRIPT_URL               : /ilias/ilias.php
SCRIPT_URI               : https://kivinet.de/ilias/ilias.php
HTTPS                    : on
SSL_TLS_SNI              : kivinet.de
HTTP_HOST                : kivinet.de
HTTP_CONNECTION          : keep-alive
HTTP_SEC_CH_UA           : "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"
HTTP_SEC_CH_UA_MOBILE    : ?0
HTTP_SEC_CH_UA_PLATFORM  : "Windows"
HTTP_UPGRADE_INSECURE_REQUESTS: 1
HTTP_DNT                 : 1
HTTP_USER_AGENT          : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
HTTP_ACCEPT              : text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
HTTP_SEC_FETCH_SITE      : same-origin
HTTP_SEC_FETCH_MODE      : navigate
HTTP_SEC_FETCH_USER      : ?1
HTTP_SEC_FETCH_DEST      : document
HTTP_REFERER             : https://kivinet.de/ilias/ilias.php?ref_id=350604&cmd=editProperties&cmdClass=ilobjbigbluebuttongui&cmdNode=r6:me&baseClass=ilobjplugindispatchgui
HTTP_ACCEPT_ENCODING     : gzip, deflate, br
HTTP_ACCEPT_LANGUAGE     : de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
HTTP_COOKIE              : ilClientId=iliasschoolmaster; PHPSESSID=pl9e2 (SHORTENED FOR SECURITY); ilClientId=iliasschoolmaster; il_mb_slates={"engaged":true}; 1044257661={"any_entry_engaged":true,"tools_engaged":false,"more_available":true,"entries":{"0:0":[0,0,0],"0:1":[0,1,0],"0:1:0":[0,1,0],"0:1:8":[0,0,0],"0:2":[0,0,0],"0:3":[0,0,0],"0:4":[0,0,0],"0:5":[0,0,0],"0:6":[0,0,0],"0:7":[0,0,0],"0:7:0":[0,0,0],"0:7:1":[0,1,0],"0:7:3":[0,1,0],"0:7:4":[0,0,0],"0:7:5":[0,0,0],"0:7:6":[0,0,0],"0:7:8":[0,0,0],"0:7:9":[0,1,0],"0:7:10":[0,0,0],"0:8":[0,0,0],"0:9":[0,0,0]},"tools":{},"known_tools":[],"last_active_top":"0:1"}
HTTP_SEC_GPC             : 1
PATH                     : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
SERVER_SIGNATURE         : <address>Apache/2.4.29 (Ubuntu) Server at kivinet.de Port 443</address>
                         
SERVER_SOFTWARE          : Apache/2.4.29 (Ubuntu)
SERVER_NAME              : kivinet.de
SERVER_ADDR              : 62.138.184.135
SERVER_PORT              : 443
REMOTE_ADDR              : 185.123.7.54
DOCUMENT_ROOT            : /var/www/html
REQUEST_SCHEME           : https
CONTEXT_PREFIX           : 
CONTEXT_DOCUMENT_ROOT    : /var/www/html
SERVER_ADMIN             : wolfgang.huebsch@kivinan.de
SCRIPT_FILENAME          : /var/www/html/ilias/ilias.php
REMOTE_PORT              : 56494
GATEWAY_INTERFACE        : CGI/1.1
SERVER_PROTOCOL          : HTTP/1.1
REQUEST_METHOD           : GET
QUERY_STRING             : ref_id=350604&cmd=showContent&cmdClass=ilobjbigbluebuttongui&cmdNode=r6:me&baseClass=ilobjplugindispatchgui
REQUEST_URI              : /ilias/ilias.php?ref_id=350604&cmd=showContent&cmdClass=ilobjbigbluebuttongui&cmdNode=r6:me&baseClass=ilobjplugindispatchgui
SCRIPT_NAME              : /ilias/ilias.php
PHP_SELF                 : /ilias/ilias.php
REQUEST_TIME_FLOAT       : 1669647160.8174
REQUEST_TIME             : 1669647160

-- Environment Variables --

empty

**Comment by wolfganghuebsch** [comment]
With version 1.0.15 I can only open old rooms. When I create a newone, the is the result:

<response>
<returncode>FAILED</returncode>
<message>We could not find a meeting with that meeting ID</message>
<messageKey>notFound</messageKey>
</response>

**Comment by wolfganghuebsch** [comment]
> With version 1.0.15 I can only open old rooms. When I create a newone, the is the result:
> 
> FAILED We could not find a meeting with that meeting ID notFound

I found out that this means, that there are not enough licences left by the server. The moodle plugin can feedback this more exactly: "Sie haben nicht mehr genug freie Konferenzverbindungen, um diese Konferenz zu starten oder Ihre Teilnehmerzahl \u00fcbersteigt das Teilnehmerlimit pro Konferenz."

**Comment by xJuvi** [comment]
Hi Wolfgang,
the creation of the meeting fails. With the plugin version 2.0 the API has been changed to the official API. This throws exceptions, which the plugin currently does not catch. This is how the error messages are generated. If the error messages were intercepted, more precise information could also be given.

You can see the HTTP Code 501 in your error messages. This indicates a misconfiguration on the server itself. Are you using Apache2 or NGINX? Do you change POST data in the web server or restrict it to selected formats?

Best regards

**Comment by xJuvi** [comment]
hi @wolfganghuebsch 
could you test, fix and try again? Does it work now?
When does the error occours? If you click on the link to join a meeting oder while create a new meeting?

Kind regards
