### ISSUE TITLE
Compatibility with ILIAS 8

### ISSUE THREAD

**Issue by felix-wo** [Minervis-GmbH/BigBlueButton-Ilias-Plugin#48]
May I ask: What’s the perspective to have compatibility with ILIAS 8?

Thank you!

**Comment by jeph864** [comment]
Dear @felix-wo,
I'm working on an update.

**Comment by ChristianWeidel** [comment]
Hello,

is there an approximate event horizon when the plug-in will be ready? 
Something like 6-8 weeks for example.

Thanks a lot for your great work.

**Comment by jeph864** [comment]
Plugin is now compatible with ILIAS8
