### ISSUE TITLE
Link/Menu Item "Learn Analytics Dashboard" is missing

### ISSUE THREAD

**Issue by haary** [Minervis-GmbH/BigBlueButton-Ilias-Plugin#54]
When clicking the "Manage User" gear the Link to the  Learn Analytics Dashboard is missing. It appears when using Greenlight and other plugins (e.g. Moodle BBB-Plugin). 

Screenshot from Greenlight:
![Bildschirmfoto_2023-10-31_09-25-12](https://github.com/Minervis-GmbH/BigBlueButton-Ilias-Plugin/assets/4052999/8153e961-4e37-4f75-903c-a4774ba45049)

**Comment by xJuvi** [comment]
Hi there,
this bug should be fixed with pr #53
