### ISSUE TITLE
Type Error, already fixed in master. Merge to release_8 missing.

### ISSUE THREAD

**Issue by swischniak** [Minervis-GmbH/BigBlueButton-Ilias-Plugin#64]
Log:
TypeError thrown with message "Argument 1 passed to ilObjBigBlueButton::setMaxConcurrentSessionsMsg() must be of the type string, null given, called in /srv/www/lernportal.bgbau.de/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/BigBlueButton/classes/class.ilObjBigBlueButton.php on line 204"

This bug is already fixed in master:
https://github.com/Minervis-GmbH/BigBlueButton-Ilias-Plugin/blob/b2053fe5837796a9b96e91cfeac569251b537d5d/classes/class.ilObjBigBlueButton.php#L204

As well as many other fixes, it seems. Is there a reason, this fixes are not merged to release_8?

**Comment by xJuvi** [comment]
Maybe you can change to the master branch? It's the branch with the most recent fixes.

**Comment by swischniak** [comment]
Of course we can switch the branch (so we did now). But the existence of branch release_8 is misleading. If everyone is supposed to use master, the other branches could be hidden or deleted. Otherwise many user could be running in issues, which a fixed in master already.

Just a suggestion.
