### ISSUE TITLE
Wrong Link after Plugin Update

### ISSUE THREAD

**Issue by wolfganghuebsch** [Minervis-GmbH/BigBlueButton-Ilias-Plugin#8]
After updating the Plugin to the latest Version (1.0.11) the URL to the BBB room is wrong. Example: https://bbblkrow.bbs-ilias.deapi/join?meetingID=ilias-bbb_info_812_1&fullName=Wolfgang+H%C3%BCbsch&password=eeeeee&checksum=eeeee
Have a look at this part: lias.deapi

**Comment by jephteaSudo** [comment]
when you add /bigbluebutton/ after the server name, this will work. In your case it should be  https://bbblkrow.bbs-ilias.de/bigbluebutton/
